### ISSUE TITLE
Add error pages for irrelevant search terms 

### ISSUE THREAD

**Issue by daminisatya** [daminisatya/SentimentVisualizer#3]

**Comment by ashwini0529** [comment]
@daminisatya  Can you please describe that what do you mean by irrelevant search terms? 
And how do you want to categorize error pages?

**Comment by daminisatya** [comment]
@ashwini0529 as of now, im using the data from loklak(which is a twitter scraper). So the search terms are the relevant hashtags which are used in the tweets. when there is a random text being entered , (for which we get zero results) it must be redirected to 404 kinda of page. Thanks for the interest in the project, you are free to report any issue or enhancement which you feel would be helpful.

**Comment by ashwini0529** [comment]
Alright. I'll look into the issue. Working on it.

**Comment by ashwini0529** [comment]
@daminisatya  please look into [this](https://github.com/daminisatya/SentimentVisualizer/pull/4)
